# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 307595dfa0be072fc3b27915be04127a789b49890c16cb0e6f1219ee6fb20c323492d678b04ff9425f172808dc30bbf8d195d143f6c0779a61c9d5262a39687b

test:
  secret_key_base: 100eb56c53caa6395f0e5484a726015109a689420df1687bff129ae02a625f7ff60fe58c5685fb1a60cb44ceeeae4b2fbfee0686302f10d409c15a9311c99b4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
